---
- name: Set SubjectAltName as a fact
  set_fact:
    IP_subject_alt_name: "{{ (IP_subject_alt_name if tiad_provider == 'local' else cloud_instance_ip) | lower }}"

- name: Add the server to an inventory group
  add_host:
    name: "{% if cloud_instance_ip == 'localhost' %}localhost{% else %}{{ cloud_instance_ip }}{% endif %}"
    groups: workshop-host
    ansible_connection: "{% if cloud_instance_ip == 'localhost' %}local{% else %}ssh{% endif %}"
    ansible_ssh_user: "{{ ansible_ssh_user }}"
    ansible_python_interpreter: "/usr/bin/python3"
    tiad_provider: "{{ tiad_provider }}"
    tiad_server_name_prefix: "{{ tiad_server_name_prefix }}"
    IP_subject_alt_name: "{{ IP_subject_alt_name }}"

- name: Additional variables for the server
  add_host:
    name: "{% if cloud_instance_ip == 'localhost' %}localhost{% else %}{{ cloud_instance_ip }}{% endif %}"
    ansible_ssh_private_key_file: "{{ SSH_keys.private }}"
  when: tiad_provider != 'local'

- name: Wait for SSH to become available
  wait_for:
    port: 22
    host: "{{ cloud_instance_ip }}"
    search_regex: "OpenSSH"
    delay: 10
    timeout: 320
    state: present
  when: cloud_instance_ip != "localhost"

- debug:
    var: IP_subject_alt_name

- name: A short pause, in order to be sure the instance is ready
  pause:
    seconds: 20
